---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ghcr-pull-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAU3xeNV5P14P1oUwG8vhrRKI2MsHnwHhFHifQOq1LvgN5vgtZncXjTZFHyXCFl1t4Bur3ncJvzgXRowovl3eYJ5Q0/CiHjerKXIrpP2EdvV6RonZ2yR4M+ikY/DXz/SP3ccC6gNrYHaxlfr3EBuATlAZfNPfnaGozWBkpZC+BcztSylAjWu7njizBwKm0Wpuy6Tzyw2mJW4F9H36zmFP2loWkroBBPtKtzo7Q8KMsexmRY/tjQOC/G9P1yPvHGK9IQz93tgEn36XEadIRnkBrz/BCkhrWuqBI5MHj7cm8/zy4/RxzBkDmCat30LeDiyB9FMLoF8j77DxuKnP1etBo5gzx3nQ29FoFSLt49LlQYWLaDFMrroK6wOxCm6SqTr7XYAdE6pnsg2wbE+yW5XjJud+96CpP222JIoboPwKTNeyGnhhO4JCxffNoq59eY5B3VgFhE9xfNfNvj8DVC+zJGai3S1brPfSyh1qTsnWfK7CCDXeIhwTtJsyDtkY3/sLrIhkWtYjmKYByEhw5eiUasg97+CnsAqOcF0XGGaXH/G2k7hz5B1/oNCx+dmt/MHKeX4rLot9zXllqIyY4EcKHeSXvxdEQUV/HSPm80HwB73ybOhQVUQ7FNXzYmlE/asMI5qFbt3FLeC8vgx/S+R9ZZziDoDPATuNp6+C5cjJlG+Hh8r6sPDvDz4kwsxGevPHMyGSLOxT7gTi1VOk6s83GWhAdQQA/seDZBAaja8uoXYmqjopULGe7Cb/LXECsPqbCuwUoH8bRYqJ9mdU6WuIjth3mZ8nJJixuv9+hg4YTfOrz1qoqaoZ4qh7gPj7km4vvhPIwIEiyQcyszzxwrTLTJqdjhgttGRwePuMQ4VSXbOdL4+meDLzk0G5dkbDCVZNqJzjTeztHnZ+Ie0a0wM16Zqzps9fB4ng3UOku0YLhuQaopBg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        kubed.appscode.com/sync: "" 
      name: ghcr-pull-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
