apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodpecker-ci
  namespace: woodpecker
spec:
  chart:
    spec:
      chart: woodpecker
      sourceRef:
        kind: HelmRepository
        name: woodpecker
      version: 3.0.6
  interval: 1m0s