apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: woodpecker-ci
  namespace: woodpecker
spec:
  chartRef:
    kind: OCIRepository
    name: woodpecker-oci
    namespace: woodpecker
  interval: 10m0s