apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../woodpecker/namespace.yaml
- ../woodpecker/repository.yaml
- ../woodpecker/release.yaml
