- hosts: nucbox
  become: true
  tasks:
    - name: Install K3s (master)
      shell: curl -sfL https://get.k3s.io | sh -s - --disable=traefik --write-kubeconfig-mode 644

    - name: Get K3s join token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Copy token to local machine
      local_action: copy content={{ k3s_token.stdout }} dest=~/k3s_token.txt

- name: Install FluxCD on K3s Cluster
  hosts: nucbox
  become: true
  vars_files:
    - secrets.yaml

  tasks:
    - name: Install Flux CLI
      shell: |
        curl -s https://fluxcd.io/install.sh | bash

    - name: Export GitHub Token as an environment variable
      shell: echo "GITHUB_TOKEN={{ github_pat }}" >> /etc/environment
      environment:
        GITHUB_TOKEN: "{{ github_pat }}"

    - name: Bootstrap Flux with GitHub
      shell: |
        flux bootstrap github \
          --owner=NickG22293 \
          --repository=homelab-iac \
          --branch=main \
          --path=clusters/my-cluster \
          --personal \
          --kubeconfig /etc/rancher/k3s/k3s.yaml 
      environment:
        GITHUB_TOKEN: "{{ github_pat }}"

# once onboarding RPi 
# - hosts: worker1,worker2
#   become: true
#   tasks:
#     - name: Install K3s (workers)
#       shell: |
#         curl -sfL https://get.k3s.io | K3S_URL="https://10.0.0.196:6443" K3S_TOKEN="{{ lookup('file', '~/k3s_token.txt') }}" sh -
