all:
  hosts:
    # Master node
    nucbox:
      ansible_host: 10.0.0.196
      ansible_user: nick
      ansible_ssh_private_key_file: ~/.ssh/primary_rsa
    # eventual Worker
    # raspberrypi:
      # ansible_host: 192.168.1.101
