apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCeYTVqGA6MD1ekH1qbVlEFyAbqyGnKmWnRKW13lg2ystaHGHCM+Crvum0Gbc8xhe1NJvoSDQrsK14DZyIIiC2yA07ANlyoiOF2yDphQcW6fm+fl5Jrlq9F0qROyLsIHgVRcsarkDSyYJe/uiYp/l8/B6/IYMOV0ecaNSipJ7wHFolxrw3PjEtTT2p6iFHjewrOrH2Qks3UbSwRFpIIGhHZ6cCUmwm/5wblYdXMQfUlzOpJHvVOdSvWr0XHm4mh7NvTUB8F1GYgP6Bmvtyw7Waj60KSeEsYxc4gzc6xFIV6JGoUmaBBpvyQtMpagHkh8rihSafOsoDrM9Bj8TNWyxdEUipbvsjeVkriVwhuiP2fMLJPB7alSSofuDjWcuOYFRq79bLkjjwAih+ifOeV+8NS1AnTmZRNOZufGMKwumeA1w8YfO3j86hZiUvg3k9v+m4WcrMYmpjGymATYLVqzsQvLRprByfRwWRp/w238UG/kGTOffW9AkjUZHcNmquH+gN72P0tpY7ukZjclYM7JPAm+zczutijBztPy4shtXhykTD42sNCPPAMxlhsAnrfJs29jI2Z5MHP9s/r/4JVvB5ydK79whhm4FlzhRKvO20MilfspLRU7BIddgUGX9CKnBc3rLYU/TCVb1v2ChAI2ZgPr2MGxA0np6Lo0NfsRclpWeO+/VEG3XWjrg2Oshjw/9oitrQfGEXoinRI6l8+SwVnJoBL/HwtHxNvbSvBIHwijZQDnH70AqW328dRBF5OGu8LdIi2sRtCgQpjmcbJ0GK+3LNhmE5ALAKVA6X8GFzF09r2pYO32u/VnuTrBuUWbPK+t3ynFF+ESSJFZKP1ldSQjTRKJEQ8guOyDA1pIR5EtStPBDN6uO8w7mF3ESyA9f1FRFUT0WnN+tkdLKpY4R5n6TqdB1Gce2ivL6rf/ygaR4n0LD4=
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared