# Release and helm repository for FluxCD for kubed 
kind: HelmRepository
apiVersion: source.toolkit.fluxcd.io/v1
metadata:
  name: kubed
  namespace: kube-system
spec: 
  interval: 5m 
  url: https://charts.appscode.com/stable/
--- 
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubed
  namespace: kube-system
spec:
  interval: 3m 
  timeout: 5m
  chart:
    spec:
      chart: kubed
      version: '0.13.2'
      sourceRef:
        kind: HelmRepository
        name: kubed
      interval: 5m
  values: 
    operator: 
      registry: rancher
      image: mirrored-appscode-kubed
      tag: v0.13.2

